### ISSUE TITLE
node . issue

### ISSUE THREAD

**Issue by The007Programmer** [Tomato6966/Discord-Rich-Presence#2]
Umm, Im having this problem after following your steps in the video. 
![image](https://user-images.githubusercontent.com/83626443/124155695-9f015880-da4b-11eb-8b67-16647e654737.png)
and I don't really know what to do. Can you please explain what to do when coming across this error?

**Comment by The007Programmer** [comment]
You may also want to update the tutorial in your README.md.

**Comment by Tomato6966** [comment]
learn js before u try stuff just do npm i discord-rpc
